// <auto-generated />
using System;
using Availability.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Availability.Infrastructure.Migrations
{
    [DbContext(typeof(AvailabilityDbContext))]
    [Migration("20260810191817_AddBookingIdToSeatLock")]
    partial class AddBookingIdToSeatLock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Availability.Domain.Entities.SeatLock", b =>
                {
                    b.Property<Guid>("LockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LockId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("OfferId", "Status");

                    b.ToTable("SeatLocks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
